version: '3.2'
services:
  app:
    image: node:19-alpine
    working_dir: /app/aie
    volumes:
      - .:/app/aie
    command: npm start
    env_file:
      - .env
      - .env.local
    networks:
      - backend
    depends_on:
      - db
  db:
    image: ankane/pgvector
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=hello
    networks:
      - backend

networks:
  backend: null

volumes:
  db-data: null
